const foods = [
    {
        id: 1,
        name: 'Burger',
        price: 5.99,
        category: 'Fast Food',
        ingredients: ['Beef patty', 'Cheese', 'Lettuce', 'Tomato'],
        location: 'Local Restaurant',
      },
    {
        id: 2,
        name: 'Margherita Pizza',
        price: 8.99,
        category: 'Pizza',
        ingredients: ['Tomato sauce', 'Mozzarella cheese', 'Basil'],
        location: 'Pizzeria',
      },
    {
        id: 3,
        name: 'Chicken Caesar Salad',
        price: 7.49,
        category: 'Salad',
        ingredients: ['Grilled chicken', 'Romaine lettuce', 'Parmesan cheese', 'Caesar dressing'],
        location: 'Salad Bar',
      },
    {
        id: 4,
        name: 'Sushi Roll Combo',
        price: 12.99,
        category: 'Sushi',
        ingredients: ['Rice', 'Nori', 'Fish', 'Vegetables'],
        location: 'Sushi Bar',
      },
    {
        id: 5,
        name: 'Pasta Carbonara',
        price: 9.99,
        category: 'Italian',
        ingredients: ['Pasta', 'Bacon', 'Eggs', 'Parmesan cheese'],
        location: 'Italian Trattoria',
      },
    {
        id: 6,
        name: 'Chicken Burrito',
        price: 8.49,
        category: 'Mexican',
        ingredients: ['Grilled chicken', 'Rice', 'Beans', 'Salsa', 'Guacamole'],
        location: 'Mexican Restaurant',
      },
    {
        id: 7,
        name: 'Vegetarian Stir-Fry',
        price: 6.99,
        category: 'Asian',
        ingredients: ['Tofu', 'Mixed vegetables', 'Soy sauce', 'Noodles'],
        location: 'Asian Fusion',
      },
    {
        id: 8,
        name: 'Grilled Salmon',
        price: 14.99,
        category: 'Seafood',
        ingredients: ['Salmon fillet', 'Lemon', 'Herbs', 'Butter'],
        location: 'Seafood Grill',
      },
    {
        id: 9,
        name: 'Mushroom Risotto',
        price: 10.49,
        category: 'European',
        ingredients: ['Arborio rice', 'Mushrooms', 'Parmesan cheese', 'White wine'],
        location: 'Fine Dining',
      },
    {
        id: 10,
        name: 'Chicken Tikka Masala',
        price: 11.99,
        category: 'Indian',
        ingredients: ['Chicken', 'Tomato sauce', 'Cream', 'Spices'],
        location: 'Indian Cuisine',
      },
    {
        id: 11,
        name: 'Greek Salad',
        price: 7.99,
        category: 'Mediterranean',
        ingredients: ['Cucumbers', 'Tomatoes', 'Feta cheese', 'Olives'],
        location: 'Mediterranean Cafe',
      },
    {
        id: 12,
        name: 'Pho Soup',
        price: 9.49,
        category: 'Vietnamese',
        ingredients: ['Rice noodles', 'Beef broth', 'Beef slices', 'Herbs'],
        location: 'Pho Restaurant',
      },
    {
        id: 13,
        name: 'Spinach and Feta Stuffed Chicken',
        price: 12.99,
        category: 'Gourmet',
        ingredients: ['Chicken breast', 'Spinach', 'Feta cheese', 'Herbs'],
        location: 'Gourmet Bistro',
      },
    {
        id: 14,
        name: 'Shrimp Scampi',
        price: 13.99,
        category: 'Seafood',
        ingredients: ['Shrimp', 'Garlic', 'Lemon', 'White wine'],
        location: 'Italian Seafood Grill',
      },
    {
        id: 15,
        name: 'Tofu Pad Thai',
        price: 8.99,
        category: 'Thai',
        ingredients: ['Tofu', 'Rice noodles', 'Peanuts', 'Bean sprouts'],
        location: 'Thai Kitchen',
      },
    {
        id: 16,
        name: 'BBQ Pulled Pork Sandwich',
        price: 10.99,
        category: 'BBQ',
        ingredients: ['Pulled pork', 'BBQ sauce', 'Coleslaw', 'Brioche bun'],
        location: 'Smokehouse BBQ',
      },
    {
        id: 17,
        name: 'Caprese Panini',
        price: 7.99,
        category: 'Italian',
        ingredients: ['Tomato', 'Mozzarella', 'Basil', 'Balsamic glaze'],
        location: 'Panini Cafe',
      },
    {
        id: 18,
        name: 'Teriyaki Salmon Bowl',
        price: 11.49,
        category: 'Japanese',
        ingredients: ['Teriyaki-glazed salmon', 'Steamed rice', 'Broccoli', 'Carrots'],
        location: 'Teriyaki House',
      },
    {
        id: 19,
        name: 'Avocado Toast',
        price: 6.49,
        category: 'Brunch',
        ingredients: ['Avocado', 'Sourdough bread', 'Tomato', 'Poached egg'],
        location: 'Cafe',
      },
    {
        id: 20,
        name: 'Gourmet Cheese Platter',
        price: 15.99,
        category: 'Appetizer',
        ingredients: ['Assorted cheeses', 'Crackers', 'Grapes', 'Nuts'],
        location: 'Wine Bar',
      },
    
  ];
  
  export default foods;
  